### ISSUE TITLE
analyse Post object

### ISSUE THREAD

**Issue by pgradone** [pgradone/FBN#2]
Once the git branches are set (soon I hope) Using the "posts" table as a basic model, please investigate how Laravel would manage the CRUD (use bookstore exercise as example) routes creation in the controllers, model (categories of posts, inherited from the main "Post" )

**Comment by faballacisse** [comment]
Done. See pull request to merge branch fab with dev branch + email dated 27 August 2020.
[FBN Blog Preview - Final Project 09.2020.pdf](https://github.com/pgradone/FBN/files/5138802/FBN.Blog.Preview.-.Final.Project.09.2020.pdf)
