### ISSUE TITLE
email registration

### ISSUE THREAD

**Issue by pgradone** [pgradone/FBN#4]
Investigate how to send email confirmation for (standard) users' registration - only basic Laravel login/register management is already implemented into FBN

**Comment by PeterAlfonsLoch** [comment]
Found this information: https://laravel.com/docs/7.x/verification

Database needs to be adapted: https://laravel.com/docs/7.x/verification#model-preparation and: https://laravel.com/docs/7.x/verification#verification-database

**Comment by PeterAlfonsLoch** [comment]
done
