### ISSUE TITLE
create email for registration verification

### ISSUE THREAD

**Issue by pgradone** [pgradone/FBN#9]
I created a new free gmail account for automatic registration by email:
user: factbasednutrition@gmail.com
password: fbn202008.
Please find the smtp and implement this in user registration if possible. thx a LOT

**Comment by PeterAlfonsLoch** [comment]
- Mailaccount was created by @pgradone
- Need to finish the mail send stuff and use mailables to make personalized [auth mail](https://laravel.com/docs/7.x/mail#generating-mailables)
- Also set the mailable as the route to use when sending authentication.
- Testing of auth.

**Comment by PeterAlfonsLoch** [comment]
Done
